build:
  maxIssues: 0

style:
  WildcardImport:
    active: false
  MaxLineLength:
    maxLineLength: 120

complexity:
  LongParameterList:
    functionThreshold: 8
    constructorThreshold: 10
  TooManyFunctions:
    active: false

naming:
  FunctionNaming:
    functionPattern: '[a-zA-Z][a-zA-Z0-9]*'
  TopLevelPropertyNaming:
    constantPattern: '[A-Z][A-Za-z0-9]*|[a-z][a-zA-Z0-9]*'

formatting:
  TrailingCommaOnCallSite:
    active: true
    autoCorrect: true
  TrailingCommaOnDeclarationSite:
    active: true
    autoCorrect: true
